// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserManagementSystem.DAL.Context;

namespace UserManagementSystem.DAL.Migrations
{
    [DbContext(typeof(UserManagementSystemContext))]
    partial class UserManagementSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UserManagementSystem.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBlackListed")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0306550-c717-4fd0-98da-08d8548aa120"),
                            Email = "admin@gmail.com",
                            FullName = "Admin Admin",
                            IsBlackListed = false,
                            Password = "Qwerty123",
                            Role = 0,
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("a21bcb79-67a8-426a-98d6-08d8548aa120"),
                            Email = "georgi@gmail.com",
                            FullName = "Georgi Gerdzhikov",
                            IsBlackListed = false,
                            Password = "Qwerty123",
                            Role = 1,
                            Username = "georgi"
                        },
                        new
                        {
                            Id = new Guid("ca0a6dd8-518e-4ba9-98d9-08d8548aa120"),
                            Email = "mariya@gmail.com",
                            FullName = "Mariya Ivanova",
                            IsBlackListed = false,
                            Password = "Qwerty123",
                            Role = 1,
                            Username = "mariya"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
